# Generated by Django 3.0.3 on 2020-02-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(default='default.jpg', upload_to='cover_images')),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
